formatter: "markdown table"

version: ">=0.18.0"

header-from: "docs/.header.md"
footer-from: "docs/.footer.md"

output:
  file: README.md
  mode: inject
  template: |-
      <!-- BEGIN_TF_DOCS -->
      {{ .Content }}
      <!-- END_TF_DOCS -->

content: |-
  {{ .Header }}

  # Terraform documentation

  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Footer }}

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
